name: Build

on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.302

    - uses: actions/checkout@v2

    - name: Build
      run: |
        dotnet tool restore
        dotnet paket restore
        dotnet build
        bazel build //...
